from experiment import Experiment
import csv


def append_result(exp):
    result = [exp.classifier_name, exp.neg_handling, exp.fix_typo_alay, exp.tfidf, exp.positive_words, exp.negative_words, exp.harsh, 
                exp.positive_prop, exp.negative_prop, exp.harsh_prop, exp.char_ngram, exp.word_ngram, 
                exp.k_cross_val, exp.mean_score, exp.tn, exp.fp, exp.fn, exp.tp, exp.precision, exp.recall, exp.f1]
    results.append(result)
    print(exp.mean_score, exp.tn, exp.fp, exp.fn, exp.tp, exp.precision, exp.recall, exp.f1)
    


results = [['classifier', 'negation_handling', 'fix_typo', 'tfidf', 'positive words', 'negative words', 'harsh words', 'positive proportion', 
            'negative proportion', 'harsh proportion', 'char n-gram', 'word n-gram', 'k_cross_val', 
            'f1_weighted', 'tn', 'fp', 'fn', 'tp', 'precision', 'recall', 'f1']]

k = 10
input_data = 'data/dataset.csv'

# params: input_file, classifier, positive_words, negative_words, harsh_words, positive_prop, negative_prop, harsh_prop, char_ngram, word_ngram, k_cross_val

# 1 feature
exp = Experiment(input_data, False, False, "rfdt", True, False, False, False, False, False, False, False, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, False, False, "rfdt", False, True, False, False, True, False, False, False, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, False, False, "rfdt", False, False, True, False, False, True, False, False, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, False, False, "rfdt", False, False, False, True, False, False, True, False, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, False, False, "rfdt", False, False, False, False, False, False, False, True, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, False, False, "rfdt", False, False, False, False, False, False, False, False, True, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, False, False, "log_reg", True, False, False, False, False, False, False, False, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, False, False, "log_reg", False, True, False, False, True, False, False, False, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, False, False, "log_reg", False, False, True, False, False, True, False, False, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, False, False, "log_reg", False, False, False, True, False, False, True, False, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, False, False, "log_reg", False, False, False, False, False, False, False, True, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, False, False, "log_reg", False, False, False, False, False, False, False, False, True, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, False, False, "svm", True, False, False, False, False, False, False, False, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, False, False, "svm", False, True, False, False, True, False, False, False, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, False, False, "svm", False, False, True, False, False, True, False, False, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, False, False, "svm", False, False, False, True, False, False, True, False, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, False, False, "svm", False, False, False, False, False, False, False, True, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, False, False, "svm", False, False, False, False, False, False, False, False, True, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, True, False, "rfdt", True, False, False, False, False, False, False, False, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, True, False, "rfdt", False, True, False, False, True, False, False, False, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, True, False, "rfdt", False, False, True, False, False, True, False, False, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, True, False, "rfdt", False, False, False, True, False, False, True, False, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, True, False, "rfdt", False, False, False, False, False, False, False, True, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, True, False, "rfdt", False, False, False, False, False, False, False, False, True, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, True, False, "log_reg", True, False, False, False, False, False, False, False, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, True, False, "log_reg", False, True, False, False, True, False, False, False, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, True, False, "log_reg", False, False, True, False, False, True, False, False, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, True, False, "log_reg", False, False, False, True, False, False, True, False, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, True, False, "log_reg", False, False, False, False, False, False, False, True, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, True, False, "log_reg", False, False, False, False, False, False, False, False, True, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, True, False, "svm", True, False, False, False, False, False, False, False, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, True, False, "svm", False, True, False, False, True, False, False, False, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, True, False, "svm", False, False, True, False, False, True, False, False, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, True, False, "svm", False, False, False, True, False, False, True, False, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, True, False, "svm", False, False, False, False, False, False, False, True, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, True, False, "svm", False, False, False, False, False, False, False, False, True, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, True, True, "rfdt", True, False, False, False, False, False, False, False, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, True, True, "rfdt", False, True, False, False, True, False, False, False, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, True, True, "rfdt", False, False, True, False, False, True, False, False, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, True, True, "rfdt", False, False, False, True, False, False, True, False, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, True, True, "rfdt", False, False, False, False, False, False, False, True, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, True, True, "rfdt", False, False, False, False, False, False, False, False, True, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, True, True, "log_reg", True, False, False, False, False, False, False, False, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, True, True, "log_reg", False, True, False, False, True, False, False, False, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, True, True, "log_reg", False, False, True, False, False, True, False, False, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, True, True, "log_reg", False, False, False, True, False, False, True, False, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, True, True, "log_reg", False, False, False, False, False, False, False, True, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, True, True, "log_reg", False, False, False, False, False, False, False, False, True, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, True, True, "svm", True, False, False, False, False, False, False, False, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, True, True, "svm", False, True, False, False, True, False, False, False, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, True, True, "svm", False, False, True, False, False, True, False, False, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, True, True, "svm", False, False, False, True, False, False, True, False, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, True, True, "svm", False, False, False, False, False, False, False, True, False, 10)
exp.run()
append_result(exp)
exp = Experiment(input_data, True, True, "svm", False, False, False, False, False, False, False, False, True, 10)
exp.run()
append_result(exp)

# # write results into output file
with open("data/output/result_1_feature.csv",'w') as f:
    wr = csv.writer(f, dialect='excel')
    wr.writerows(results)


# # 2 features
# results = [['classifier', 'negation_handling', 'fix_typo', 'tfidf', 'positive words', 'negative words', 'harsh words', 'positive proportion', 
#             'negative proportion', 'harsh proportion', 'char n-gram', 'word n-gram', 'k_cross_val', 
#             'f1_weighted', 'tn', 'fp', 'fn', 'tp', 'precision', 'recall', 'f1']]

# exp = Experiment(input_data, False, False, "rfdt", True, True, False, False, True, False, False, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", True, False, True, False, False, True, False, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", True, False, False, True, False, False, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", True, False, False, False, False, False, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", True, False, False, False, False, False, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", False, True, True, False, True, True, False, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", False, True, False, True, True, False, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", False, True, False, False, True, False, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", False, True, False, False, True, False, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", False, False, True, True, False, True, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", False, False, True, False, False, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", False, False, True, False, False, True, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", False, False, False, False, False, False, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", True, True, False, False, True, False, False, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", True, False, True, False, False, True, False, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", True, False, False, True, False, False, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", True, False, False, False, False, False, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", True, False, False, False, False, False, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", False, True, True, False, True, True, False, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", False, True, False, True, True, False, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", False, True, False, False, True, False, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", False, True, False, False, True, False, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", False, False, True, True, False, True, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", False, False, True, False, False, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", False, False, True, False, False, True, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", False, False, False, False, False, False, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", True, True, False, False, True, False, False, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", True, False, True, False, False, True, False, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", True, False, False, True, False, False, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", True, False, False, False, False, False, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", True, False, False, False, False, False, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", False, True, True, False, True, True, False, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", False, True, False, True, True, False, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", False, True, False, False, True, False, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", False, True, False, False, True, False, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", False, False, True, True, False, True, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", False, False, True, False, False, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", False, False, True, False, False, True, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", False, False, False, False, False, False, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", True, True, False, False, True, False, False, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", True, False, True, False, False, True, False, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", True, False, False, True, False, False, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", True, False, False, False, False, False, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", True, False, False, False, False, False, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", False, True, True, False, True, True, False, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", False, True, False, True, True, False, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", False, True, False, False, True, False, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", False, True, False, False, True, False, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", False, False, True, True, False, True, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", False, False, True, False, False, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", False, False, True, False, False, True, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", False, False, False, False, False, False, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", True, True, False, False, True, False, False, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", True, False, True, False, False, True, False, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", True, False, False, True, False, False, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", True, False, False, False, False, False, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", True, False, False, False, False, False, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", False, True, True, False, True, True, False, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", False, True, False, True, True, False, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", False, True, False, False, True, False, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", False, True, False, False, True, False, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", False, False, True, True, False, True, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", False, False, True, False, False, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", False, False, True, False, False, True, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", False, False, False, False, False, False, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", True, True, False, False, True, False, False, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", True, False, True, False, False, True, False, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", True, False, False, True, False, False, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", True, False, False, False, False, False, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", True, False, False, False, False, False, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", False, True, True, False, True, True, False, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", False, True, False, True, True, False, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", False, True, False, False, True, False, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", False, True, False, False, True, False, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", False, False, True, True, False, True, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", False, False, True, False, False, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", False, False, True, False, False, True, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", False, False, False, False, False, False, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", True, True, False, False, True, False, False, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", True, False, True, False, False, True, False, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", True, False, False, True, False, False, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", True, False, False, False, False, False, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", True, False, False, False, False, False, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", False, True, True, False, True, True, False, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", False, True, False, True, True, False, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", False, True, False, False, True, False, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", False, True, False, False, True, False, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", False, False, True, True, False, True, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", False, False, True, False, False, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", False, False, True, False, False, True, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", False, False, False, False, False, False, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", True, True, False, False, True, False, False, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", True, False, True, False, False, True, False, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", True, False, False, True, False, False, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", True, False, False, False, False, False, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", True, False, False, False, False, False, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", False, True, True, False, True, True, False, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", False, True, False, True, True, False, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", False, True, False, False, True, False, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", False, True, False, False, True, False, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", False, False, True, True, False, True, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", False, False, True, False, False, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", False, False, True, False, False, True, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", False, False, False, False, False, False, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", True, True, False, False, True, False, False, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", True, False, True, False, False, True, False, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", True, False, False, True, False, False, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", True, False, False, False, False, False, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", True, False, False, False, False, False, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", False, True, True, False, True, True, False, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", False, True, False, True, True, False, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", False, True, False, False, True, False, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", False, True, False, False, True, False, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", False, False, True, True, False, True, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", False, False, True, False, False, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", False, False, True, False, False, True, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", False, False, False, False, False, False, False, True, True, 10)
# exp.run()
# append_result(exp)

# with open("data/output/result_balancing_2_features.csv",'w') as f:
#     wr = csv.writer(f, dialect='excel')
#     wr.writerows(results)

# # # 3 features

# results = [['classifier', 'negation_handling', 'fix_typo', 'tfidf', 'positive words', 'negative words', 'harsh words', 'positive proportion', 
#             'negative proportion', 'harsh proportion', 'char n-gram', 'word n-gram', 'k_cross_val', 
#             'f1_weighted', 'tn', 'fp', 'fn', 'tp', 'precision', 'recall', 'f1']]

# exp = Experiment(input_data, False, False, "rfdt", True, True, True, False, True, True, False, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", True, True, False, True, True, False, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", True, True, False, False, True, False, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", True, True, False, False, True, False, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", True, False, True, True, False, True, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", True, False, True, False, False, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", True, False, True, False, False, True, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", True, False, False, True, False, False, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", True, False, False, True, False, False, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", True, False, False, False, False, False, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", False, True, True, True, True, True, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", False, True, True, False, True, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", False, True, True, False, True, True, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", False, False, True, True, False, True, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", False, False, True, True, False, True, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", False, False, True, False, False, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", False, False, False, True, False, False, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", True, True, True, False, True, True, False, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", True, True, False, True, True, False, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", True, True, False, False, True, False, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", True, True, False, False, True, False, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", True, False, True, True, False, True, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", True, False, True, False, False, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", True, False, True, False, False, True, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", True, False, False, True, False, False, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", True, False, False, True, False, False, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", True, False, False, False, False, False, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", False, True, True, True, True, True, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", False, True, True, False, True, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", False, True, True, False, True, True, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", False, False, True, True, False, True, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", False, False, True, True, False, True, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", False, False, True, False, False, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", False, False, False, True, False, False, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", True, True, True, False, True, True, False, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", True, True, False, True, True, False, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", True, True, False, False, True, False, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", True, True, False, False, True, False, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", True, False, True, True, False, True, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", True, False, True, False, False, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", True, False, True, False, False, True, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", True, False, False, True, False, False, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", True, False, False, True, False, False, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", True, False, False, False, False, False, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", False, True, True, True, True, True, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", False, True, True, False, True, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", False, True, True, False, True, True, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", False, False, True, True, False, True, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", False, False, True, True, False, True, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", False, False, True, False, False, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", False, False, False, True, False, False, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", True, True, True, False, True, True, False, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", True, True, False, True, True, False, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", True, True, False, False, True, False, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", True, True, False, False, True, False, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", True, False, True, True, False, True, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", True, False, True, False, False, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", True, False, True, False, False, True, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", True, False, False, True, False, False, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", True, False, False, True, False, False, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", True, False, False, False, False, False, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", False, True, True, True, True, True, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", False, True, True, False, True, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", False, True, True, False, True, True, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", False, False, True, True, False, True, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", False, False, True, True, False, True, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", False, False, True, False, False, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", False, False, False, True, False, False, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", True, True, True, False, True, True, False, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", True, True, False, True, True, False, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", True, True, False, False, True, False, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", True, True, False, False, True, False, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", True, False, True, True, False, True, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", True, False, True, False, False, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", True, False, True, False, False, True, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", True, False, False, True, False, False, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", True, False, False, True, False, False, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", True, False, False, False, False, False, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", False, True, True, True, True, True, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", False, True, True, False, True, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", False, True, True, False, True, True, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", False, False, True, True, False, True, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", False, False, True, True, False, True, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", False, False, True, False, False, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", False, False, False, True, False, False, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", True, True, True, False, True, True, False, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", True, True, False, True, True, False, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", True, True, False, False, True, False, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", True, True, False, False, True, False, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", True, False, True, True, False, True, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", True, False, True, False, False, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", True, False, True, False, False, True, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", True, False, False, True, False, False, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", True, False, False, True, False, False, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", True, False, False, False, False, False, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", False, True, True, True, True, True, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", False, True, True, False, True, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", False, True, True, False, True, True, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", False, False, True, True, False, True, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", False, False, True, True, False, True, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", False, False, True, False, False, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", False, False, False, True, False, False, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", True, True, True, False, True, True, False, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", True, True, False, True, True, False, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", True, True, False, False, True, False, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", True, True, False, False, True, False, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", True, False, True, True, False, True, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", True, False, True, False, False, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", True, False, True, False, False, True, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", True, False, False, True, False, False, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", True, False, False, True, False, False, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", True, False, False, False, False, False, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", False, True, True, True, True, True, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", False, True, True, False, True, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", False, True, True, False, True, True, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", False, False, True, True, False, True, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", False, False, True, True, False, True, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", False, False, True, False, False, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", False, False, False, True, False, False, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", True, True, True, False, True, True, False, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", True, True, False, True, True, False, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", True, True, False, False, True, False, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", True, True, False, False, True, False, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", True, False, True, True, False, True, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", True, False, True, False, False, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", True, False, True, False, False, True, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", True, False, False, True, False, False, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", True, False, False, True, False, False, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", True, False, False, False, False, False, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", False, True, True, True, True, True, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", False, True, True, False, True, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", False, True, True, False, True, True, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", False, False, True, True, False, True, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", False, False, True, True, False, True, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", False, False, True, False, False, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", False, False, False, True, False, False, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", True, True, True, False, True, True, False, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", True, True, False, True, True, False, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", True, True, False, False, True, False, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", True, True, False, False, True, False, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", True, False, True, True, False, True, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", True, False, True, False, False, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", True, False, True, False, False, True, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", True, False, False, True, False, False, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", True, False, False, True, False, False, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", True, False, False, False, False, False, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", False, True, True, True, True, True, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", False, True, True, False, True, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", False, True, True, False, True, True, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", False, False, True, True, False, True, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", False, False, True, True, False, True, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", False, False, True, False, False, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", False, False, False, True, False, False, True, True, True, 10)
# exp.run()
# append_result(exp)

# with open("data/output/result_balancing_3_features.csv",'w') as f:
#     wr = csv.writer(f, dialect='excel')
#     wr.writerows(results)

# # # 4 features

# results = [['classifier', 'negation_handling', 'fix_typo', 'tfidf', 'positive words', 'negative words', 'harsh words', 'positive proportion', 
#             'negative proportion', 'harsh proportion', 'char n-gram', 'word n-gram', 'k_cross_val', 
#             'f1_weighted', 'tn', 'fp', 'fn', 'tp', 'precision', 'recall', 'f1']]

# exp = Experiment(input_data, False, False, "rfdt", True, True, True, True, True, True, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", True, True, True, False, True, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", True, True, True, False, True, True, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", True, True, False, True, True, False, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", True, True, False, True, True, False, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", True, True, False, False, True, False, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", True, False, True, True, False, True, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", True, False, True, True, False, True, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", True, False, True, False, False, True, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", True, False, False, True, False, False, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", False, True, True, True, True, True, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", False, True, True, True, True, True, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", False, True, True, False, True, True, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", False, True, False, True, True, False, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", False, False, True, True, False, True, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", True, True, True, True, True, True, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", True, True, True, False, True, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", True, True, True, False, True, True, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", True, True, False, True, True, False, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", True, True, False, True, True, False, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", True, True, False, False, True, False, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", True, False, True, True, False, True, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", True, False, True, True, False, True, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", True, False, True, False, False, True, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", True, False, False, True, False, False, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", False, True, True, True, True, True, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", False, True, True, True, True, True, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", False, True, True, False, True, True, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", False, True, False, True, True, False, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", False, False, True, True, False, True, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", True, True, True, True, True, True, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", True, True, True, False, True, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", True, True, True, False, True, True, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", True, True, False, True, True, False, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", True, True, False, True, True, False, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", True, True, False, False, True, False, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", True, False, True, True, False, True, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", True, False, True, True, False, True, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", True, False, True, False, False, True, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", True, False, False, True, False, False, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", False, True, True, True, True, True, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", False, True, True, True, True, True, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", False, True, True, False, True, True, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", False, True, False, True, True, False, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", False, False, True, True, False, True, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", True, True, True, True, True, True, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", True, True, True, False, True, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", True, True, True, False, True, True, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", True, True, False, True, True, False, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", True, True, False, True, True, False, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", True, True, False, False, True, False, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", True, False, True, True, False, True, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", True, False, True, True, False, True, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", True, False, True, False, False, True, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", True, False, False, True, False, False, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", False, True, True, True, True, True, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", False, True, True, True, True, True, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", False, True, True, False, True, True, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", False, True, False, True, True, False, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", False, False, True, True, False, True, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", True, True, True, True, True, True, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", True, True, True, False, True, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", True, True, True, False, True, True, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", True, True, False, True, True, False, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", True, True, False, True, True, False, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", True, True, False, False, True, False, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", True, False, True, True, False, True, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", True, False, True, True, False, True, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", True, False, True, False, False, True, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", True, False, False, True, False, False, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", False, True, True, True, True, True, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", False, True, True, True, True, True, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", False, True, True, False, True, True, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", False, True, False, True, True, False, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", False, False, True, True, False, True, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", True, True, True, True, True, True, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", True, True, True, False, True, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", True, True, True, False, True, True, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", True, True, False, True, True, False, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", True, True, False, True, True, False, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", True, True, False, False, True, False, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", True, False, True, True, False, True, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", True, False, True, True, False, True, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", True, False, True, False, False, True, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", True, False, False, True, False, False, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", False, True, True, True, True, True, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", False, True, True, True, True, True, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", False, True, True, False, True, True, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", False, True, False, True, True, False, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", False, False, True, True, False, True, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", True, True, True, True, True, True, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", True, True, True, False, True, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", True, True, True, False, True, True, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", True, True, False, True, True, False, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", True, True, False, True, True, False, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", True, True, False, False, True, False, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", True, False, True, True, False, True, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", True, False, True, True, False, True, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", True, False, True, False, False, True, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", True, False, False, True, False, False, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", False, True, True, True, True, True, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", False, True, True, True, True, True, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", False, True, True, False, True, True, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", False, True, False, True, True, False, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", False, False, True, True, False, True, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", True, True, True, True, True, True, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", True, True, True, False, True, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", True, True, True, False, True, True, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", True, True, False, True, True, False, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", True, True, False, True, True, False, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", True, True, False, False, True, False, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", True, False, True, True, False, True, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", True, False, True, True, False, True, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", True, False, True, False, False, True, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", True, False, False, True, False, False, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", False, True, True, True, True, True, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", False, True, True, True, True, True, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", False, True, True, False, True, True, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", False, True, False, True, True, False, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", False, False, True, True, False, True, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", True, True, True, True, True, True, True, False, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", True, True, True, False, True, True, False, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", True, True, True, False, True, True, False, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", True, True, False, True, True, False, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", True, True, False, True, True, False, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", True, True, False, False, True, False, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", True, False, True, True, False, True, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", True, False, True, True, False, True, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", True, False, True, False, False, True, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", True, False, False, True, False, False, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", False, True, True, True, True, True, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", False, True, True, True, True, True, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", False, True, True, False, True, True, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", False, True, False, True, True, False, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", False, False, True, True, False, True, True, True, True, 10)
# exp.run()
# append_result(exp)
# with open("data/output/result_balancing_4_features.csv",'w') as f:
#     wr = csv.writer(f, dialect='excel')
#     wr.writerows(results)

# # # 5 features

# results = [['classifier', 'negation_handling', 'fix_typo', 'tfidf', 'positive words', 'negative words', 'harsh words', 'positive proportion', 
#             'negative proportion', 'harsh proportion', 'char n-gram', 'word n-gram', 'k_cross_val', 
#             'f1_weighted', 'tn', 'fp', 'fn', 'tp', 'precision', 'recall', 'f1']]

# exp = Experiment(input_data, False, False, "rfdt", True, True, True, True, True, True, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", True, True, True, True, True, True, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", True, True, True, False, True, True, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", True, True, False, True, True, False, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", True, False, True, True, False, True, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "rfdt", False, True, True, True, True, True, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", True, True, True, True, True, True, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", True, True, True, True, True, True, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", True, True, True, False, True, True, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", True, True, False, True, True, False, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", True, False, True, True, False, True, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", False, True, True, True, True, True, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", True, True, True, True, True, True, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", True, True, True, True, True, True, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", True, True, True, False, True, True, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", True, True, False, True, True, False, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", True, False, True, True, False, True, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", False, True, True, True, True, True, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", True, True, True, True, True, True, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", True, True, True, True, True, True, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", True, True, True, False, True, True, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", True, True, False, True, True, False, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", True, False, True, True, False, True, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", False, True, True, True, True, True, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", True, True, True, True, True, True, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", True, True, True, True, True, True, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", True, True, True, False, True, True, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", True, True, False, True, True, False, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", True, False, True, True, False, True, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", False, True, True, True, True, True, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", True, True, True, True, True, True, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", True, True, True, True, True, True, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", True, True, True, False, True, True, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", True, True, False, True, True, False, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", True, False, True, True, False, True, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", False, True, True, True, True, True, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", True, True, True, True, True, True, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", True, True, True, True, True, True, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", True, True, True, False, True, True, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", True, True, False, True, True, False, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", True, False, True, True, False, True, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", False, True, True, True, True, True, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", True, True, True, True, True, True, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", True, True, True, True, True, True, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", True, True, True, False, True, True, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", True, True, False, True, True, False, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", True, False, True, True, False, True, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", False, True, True, True, True, True, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", True, True, True, True, True, True, True, True, False, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", True, True, True, True, True, True, True, False, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", True, True, True, False, True, True, False, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", True, True, False, True, True, False, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", True, False, True, True, False, True, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", False, True, True, True, True, True, True, True, True, 10)
# exp.run()
# append_result(exp)

# with open("data/output/result_balancing_5_features.csv",'w') as f:
#     wr = csv.writer(f, dialect='excel')
#     wr.writerows(results)

# # 6 features
# exp = Experiment(input_data, False, False, "rfdt", True, True, True, True, True, True, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "log_reg", True, True, True, True, True, True, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, False, False, "svm", True, True, True, True, True, True, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "rfdt", True, True, True, True, True, True, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "log_reg", True, True, True, True, True, True, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, False, "svm", True, True, True, True, True, True, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "rfdt", True, True, True, True, True, True, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "log_reg", True, True, True, True, True, True, True, True, True, 10)
# exp.run()
# append_result(exp)
# exp = Experiment(input_data, True, True, "svm", True, True, True, True, True, True, True, True, True, 10)
# exp.run()
# append_result(exp)

# with open("data/output/result_balancing_6_features.csv",'w') as f:
#     wr = csv.writer(f, dialect='excel')
#     wr.writerows(results)
